### PR TITLE
change ficus to figus

### PR DESCRIPTION
**Pull request by Shmuelmb**
#18

### CODE REVIEW

**Comment by omridevk** [comment]
@Shmuelmb great change :) thanks a lot.
One little thing, please remove the pnpm-lock file from the PR.

**Comment by omridevk** [comment]
@Shmuelmb 
In general, when contributing to open source, it is important that the file changed are reflective of the change in the PR. 
A PR shouldn't include file changes that are not directly related to the change at hand.
Regardless, really appreciate your contribution 👯

**Comment by Shmuelmb** [comment]
Hi omri
thank you for the feedback
I removed pnpm-lock file and committed 
Let me know if you need anything else

**Comment by omridevk** [comment]
fixed by other PR.
Thanks @Shmuelmb great work!

**Pull request closed without merging**
